In [2]:
import pandas as pd

In [5]:
clean2011 = "/Users/sarikasabnis/Downloads/2011cleanslang.csv"
clean2012 = "/Users/sarikasabnis/Downloads/2012cleanslang.csv"

In [38]:
data1 = pd.read_csv(clean2011)
data2 = pd.read_csv(clean2012)

In [39]:
print(data1.shape)
data1.head()

(156518, 13)

,Unnamed: 0,time_stamp,tweet_text,state,place_name,retweeted,lolVal,famVal,swagVal,yoloVal,noobVal,pwnedVal,epicFailVal
0,0,Tue Dec 27 23:36:00 +0000 2011,my body in pain smh i could use a massage from...,CT,"Bridgeport, CT",False,0,0,0,0,0,0,0
1,1,Tue Dec 27 23:51:04 +0000 2011,me voyque lastima pero adiosme despido de tiiy...,TX,"Houston, TX",False,0,0,0,0,0,0,0
2,2,Tue Dec 27 23:30:00 +0000 2011,good tweet HASH,MA,"Grafton, MA",False,0,0,0,0,0,0,0
3,3,Tue Dec 27 23:22:02 +0000 2011,i never been,MD,"Maryland, US",False,0,0,0,0,0,0,0
4,4,Tue Dec 27 23:55:04 +0000 2011,k i gotta get dressed,AL,"Hoover, AL",False,0,0,0,0,0,0,0

In [40]:
print(data2.shape)
data3 = data2.iloc[0:156518]

(1472101, 13)

In [41]:
print(data3.shape)
data3.head()

(156518, 13)

,Unnamed: 0,time_stamp,tweet_text,state,place_name,retweeted,lolVal,famVal,swagVal,yoloVal,noobVal,pwnedVal,epicFailVal
0,0,Mon Aug 27 22:51:01 +0000 2012,just sent the vox,GA,"Columbus, GA",False,0,0,0,0,0,0,0
1,1,Mon Aug 27 22:06:01 +0000 2012,yes yumm,MO,"Hadley, MO",False,0,0,0,0,0,0,0
2,2,Mon Aug 27 22:55:01 +0000 2012,painting a wall at sunset can be challenging h...,PA,"Willow Street, PA",False,0,0,0,0,0,0,0
3,3,Mon Aug 27 22:22:01 +0000 2012,im still so young that i aint have enough of n...,VA,"Laurel, VA",False,0,0,0,0,0,0,0
4,4,Mon Aug 27 22:02:00 +0000 2012,one week left of summer damn HASHbittersweet H...,MN,"Hermantown, MN",False,0,0,0,0,0,0,0

In [42]:
df = data1.append(data3)
print(df.shape)
df

(313036, 13)

,Unnamed: 0,time_stamp,tweet_text,state,place_name,retweeted,lolVal,famVal,swagVal,yoloVal,noobVal,pwnedVal,epicFailVal
0,0,Tue Dec 27 23:36:00 +0000 2011,my body in pain smh i could use a massage from...,CT,"Bridgeport, CT",False,0,0,0,0,0,0,0
1,1,Tue Dec 27 23:51:04 +0000 2011,me voyque lastima pero adiosme despido de tiiy...,TX,"Houston, TX",False,0,0,0,0,0,0,0
2,2,Tue Dec 27 23:30:00 +0000 2011,good tweet HASH,MA,"Grafton, MA",False,0,0,0,0,0,0,0
3,3,Tue Dec 27 23:22:02 +0000 2011,i never been,MD,"Maryland, US",False,0,0,0,0,0,0,0
4,4,Tue Dec 27 23:55:04 +0000 2011,k i gotta get dressed,AL,"Hoover, AL",False,0,0,0,0,0,0,0
5,5,Tue Dec 27 23:19:06 +0000 2011,“ sexy gym hottie HASHtwitterafterdark HASHmot...,IN,"Indianapolis, IN",False,0,0,0,0,0,0,0
6,6,Tue Dec 27 23:28:09 +0000 2011,watching the wood,CA,"Inglewood, CA",False,0,0,0,0,0,0,0
7,7,Tue Dec 27 23:52:12 +0000 2011,world peace is such a big goal volunteer your ...,MA,"Boston, MA",False,0,0,0,0,0,0,0
8,8,Tue Dec 27 23:36:19 +0000 2011,time out,SC,"South Carolina, US",False,0,0,0,0,0,0,0
9,9,Tue Dec 27 23:51:04 +0000 2011,did i just end up in giants stadium orr,NJ,"East Rutherford, NJ",False,0,0,0,0,0,0,0
10,10,Tue Dec 27 23:55:05 +0000 2011,holy shit i thought all the ladies here had a ...,OH,"Montgomery, OH",False,0,0,0,0,0,0,0
11,11,Tue Dec 27 23:06:14 +0000 2011,this nigga in kentucky is too in love lmao you...,TN,"Nashville, TN",False,0,0,0,0,0,0,0
12,12,Tue Dec 27 23:02:16 +0000 2011,im at super target 5301 n garland ave at sh ga...,TX,"Garland, TX",False,0,0,0,0,0,0,0
13,13,Tue Dec 27 23:19:12 +0000 2011,it suckstwitter isnt fun anymore,MO,"Lewis and Clark, MO",False,0,0,0,0,0,0,0
14,14,Tue Dec 27 23:52:16 +0000 2011,realmente n faço ideia xd ou vc blefou ou diz ...,TX,"Houston, TX",False,0,0,0,0,0,0,0
15,15,Tue Dec 27 23:28:25 +0000 2011,young and reckless,PA,"Philadelphia, PA",False,0,0,0,0,0,0,0
16,16,Tue Dec 27 23:36:32 +0000 2011,well hes nice to me every new years day lol al...,NJ,"Garfield, NJ",False,1,0,0,0,0,0,0
17,17,Tue Dec 27 23:30:14 +0000 2011,home,GA,"Dublin, GA",False,0,0,0,0,0,0,0
18,18,Tue Dec 27 23:22:30 +0000 2011,im at walmart supercenter 25737 us route HASH1...,NY,"Calcium, NY",False,0,0,0,0,0,0,0
19,19,Tue Dec 27 23:55:13 +0000 2011,haha whats hood with you sahn,MD,"Takoma Park, MD",False,0,0,0,0,0,0,0
20,20,Tue Dec 27 23:02:18 +0000 2011,just got done with my workout been slippin on ...,AL,"Huntsville, AL",False,0,0,0,0,0,0,0
21,21,Tue Dec 27 23:19:14 +0000 2011,shopping in collierville soothes my nerves,TN,"Collierville, TN",False,0,0,0,0,0,0,0
22,22,Tue Dec 27 23:52:19 +0000 2011,damn kids quot just saw a teen walking down th...,MS,"Mississippi, US",False,0,0,0,0,0,0,0
23,23,Tue Dec 27 23:28:27 +0000 2011,a slice from johnnys in the east village per r...,NY,"Manhattan, NY",False,0,0,0,0,0,0,0
24,24,Tue Dec 27 23:36:33 +0000 2011,im that kid waiting on the side of the road fo...,CO,"Steamboat Springs, CO",False,0,0,0,0,0,0,0
25,25,Tue Dec 27 23:51:15 +0000 2011,he thought i was talking about him,LA,"Mississippi, US",False,0,0,0,0,0,0,0
26,26,Tue Dec 27 23:30:23 +0000 2011,i want to do a music video in the ball pitand ...,KS,"Kansas, US",False,0,0,0,0,0,0,0
27,27,Tue Dec 27 23:22:33 +0000 2011,outside just sitting in the car not ready to w...,GA,"Gracewood, GA",False,0,0,0,0,0,0,0
28,28,Tue Dec 27 23:55:15 +0000 2011,i hope he see it too,GA,"Macon, GA",False,0,0,0,0,0,0,0
29,29,Tue Dec 27 23:02:23 +0000 2011,colombiana pues,FL,"Miami Beach, FL",False,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156488,156488,Sat Aug 04 05:22:48 +0000 2012,do you assume hes not read the us constitution...,MD,"Ellicott City, MD",False,0,0,0,0,0,0,0
156489,156489,Sat Aug 04 05:30:37 +0000 2012,my phone gets no play,FL,"Golden Glades, FL",False,0,0,0,0,0,0,0
156490,156490,Sat Aug 04 05:02:24 +0000 2012,future new song turn off the lights straight t...,AL,"Mobile, AL",False,0,0,0,0,0,0,0
156491,156491,Sat Aug 04 05:38:22 +0000 2012,sometimes it isnt saying goodbye to the people...,PA,"Wayne Heights, PA",False,0,0,0,0,0,0,0
156492,156492,Sat Aug 04 05:55:57 +0000 2012,my favorite stephanies HASHidentity tampa,FL,"Florida, US",False,0,0,0,0,0,0,0
156493,156493,Sat Aug 04 05:38:22 +0000 2012,uwant to talk im here some tims it helps to le...,NV,"Reno North, NV",False,0,0,0,0,0,0,0
156494,156494,Sat Aug 04 05:02:28 +0000 2012,you wanted to talk at oclock last night shit t...,TN,"Memphis, TN",False,0,0,0,0,0,0,0
156495,156495,Sat Aug 04 05:22:56 +0000 2012,flashback i love u like a love song baby,CA,"Duboce Triangle, San Francisco",False,0,0,0,0,0,0,0
156496,156496,Sat Aug 04 05:42:04 +0000 2012,this lil nigga here speaking the truth,TX,"Groesbeck, TX",False,0,0,0,0,0,0,0
156497,156497,Sat Aug 04 05:11:00 +0000 2012,smores pie mcdonalds,IA,"McDonald's, Cedar Falls",False,0,0,0,0,0,0,0
156498,156498,Sat Aug 04 05:59:02 +0000 2012,theres a dude here that i will probably end up...,IL,"Labemi's, Crystal Lake",False,0,0,0,0,0,0,0
156499,156499,Sat Aug 04 05:38:26 +0000 2012,dang you slacking,AL,"Bay Minette, AL",False,0,0,0,0,0,0,0
156500,156500,Sat Aug 04 05:02:32 +0000 2012,wanna tell da world about chu so dey can jealo...,MS,"Jackson, MS",False,0,0,0,0,0,0,0
156501,156501,Sat Aug 04 05:30:55 +0000 2012,goddamn it,OH,"Xenia, OH",False,0,0,0,0,0,0,0
156502,156502,Sat Aug 04 05:31:01 +0000 2012,party and bullshit,OH,"Euclid, OH",False,0,0,0,0,0,0,0
156503,156503,Sat Aug 04 05:11:03 +0000 2012,they aren going to feed you or your pig lmao,TX,"Fairfield, TX",False,0,0,0,0,0,0,0
156504,156504,Sat Aug 04 05:42:08 +0000 2012,not even close,CO,"Redlands, CO",False,0,0,0,0,0,0,0
156505,156505,Sat Aug 04 05:30:55 +0000 2012,got trojans trynna have by the end of the night,LA,"Baton Rouge, LA",False,0,0,0,0,0,0,0
156506,156506,Sat Aug 04 05:59:06 +0000 2012,its dead af tonight,IL,"Chicago, IL",False,0,0,0,0,0,0,0
156507,156507,Sat Aug 04 05:38:30 +0000 2012,machine gun funk was maybe my favorite that an...,NE,"Offutt AFB, NE",False,0,0,0,0,0,0,0
156508,156508,Sat Aug 04 05:31:02 +0000 2012,thats what im saying i know like all the words...,MA,"South Yarmouth, MA",False,0,0,0,0,0,0,0
156509,156509,Sat Aug 04 05:59:07 +0000 2012,new furniture put together new place is coming...,CA,"Isla Vista, CA",False,0,0,0,0,0,0,0
156510,156510,Sat Aug 04 05:59:08 +0000 2012,its like every time i want u back u give me a ...,NJ,"Delaware, US",False,0,0,0,0,0,0,0
156511,156511,Sat Aug 04 05:02:36 +0000 2012,not like you talk to me anyway,TN,"Nashville, TN",False,0,0,0,0,0,0,0
156512,156512,Sat Aug 04 05:31:04 +0000 2012,my bad to all who tweeted me just got home wil...,NY,"Smithtown, NY",False,0,0,0,0,0,0,0
156513,156513,Sat Aug 04 05:42:14 +0000 2012,2,CA,"Covina, CA",False,0,0,0,0,0,0,0
156514,156514,Sat Aug 04 05:47:03 +0000 2012,i wanted to be there when charlie rocked liam ...,IL,"Minooka, IL",False,0,0,0,0,0,0,0
156515,156515,Sat Aug 04 05:42:15 +0000 2012,lol HASHclassic,WI,"Waukesha, WI",False,1,0,0,0,0,0,0
156516,156516,Sat Aug 04 05:31:05 +0000 2012,being ignoredltltltlt,PA,"South Williamsport, PA",False,0,0,0,0,0,0,0
156517,156517,Sat Aug 04 05:47:03 +0000 2012,whats ur rap name,NJ,"East Orange, NJ",False,0,0,0,0,0,0,0

In [43]:
156518+156518

313036

In [76]:
tweets_2011 = list(data1['tweet_text'])
tweets_2012 = list(data3["tweet_text"])

In [77]:
tweet_dict_2011 = {}
for tweet in tweets_2011:
    tweet = str(tweet)
    words = tweet.split()
    for word in words:
        if(word not in tweet_dict_2011.keys()):
            tweet_dict_2011[word] = 0
        else:
            tweet_dict_2011[word] += 1

# for word in tweet_dict_2011.keys():
#     if(tweet_dict_2011[word] >= 100):
#         print(word, ":", tweet_dict_2011[word])

In [88]:
tweet_dict_2012 = {}
for tweet in tweets_2012:
    tweet = str(tweet)
    words = tweet.split()
    for word in words:
        if(word not in tweet_dict_2012.keys()):
            tweet_dict_2012[word] = 0
        else:
            tweet_dict_2012[word] += 1

In [89]:
vulgarities = ["shit","damn","ass","bitch","fuck","fucking","fucked","bullshit","hell"]
words_of_interest = ["stfu","smh","asap","chillin","wat","xd","af","ugh","sis","wtf", "fam","lol","swag"]
hashtags = ["HASHgetalljobs","HASHjobs","HASHwinning"]

In [90]:
# for 2011:
vulgarities_2011,slang_2011,hashtags_2011 = {},{},{}
for word in tweet_dict_2011.keys():
    if word in vulgarities:
        vulgarities_2011.update({word:tweet_dict_2011[word]})
    elif word in words_of_interest:
        slang_2011.update({word:tweet_dict_2011[word]})
    elif word in hashtags:
        hashtags_2011.update({word:tweet_dict_2011[word]})

# for 2012:     
vulgarities_2012,slang_2012,hashtags_2012 = {},{},{}
for word in tweet_dict_2012.keys():
    if word in vulgarities:
        vulgarities_2012.update({word:tweet_dict_2012[word]})
    elif word in words_of_interest:
        slang_2012.update({word:tweet_dict_2012[word]})
    elif word in hashtags:
        hashtags_2012.update({word:tweet_dict_2012[word]})

In [91]:
vulgarities_df = [vulgarities_2011, vulgarities_2012]
vulgarities_df = pd.DataFrame(vulgarities_df, index=['2011','2012']).T

slang_df = [slang_2011,slang_2012]
slang_df = pd.DataFrame(slang_df, index=['2011','2012']).T

hashtags_df = [hashtags_2011, hashtags_2012]
hashtags_df = pd.DataFrame(hashtags_df, index=['2011','2012']).T

In [92]:
print(vulgarities_df)
print(slang_df)
print(hashtags_df)

          2011  2012
ass       1959  2034
bitch     1256  1543
bullshit   166   142
damn      1402  1345
fuck      2050  2367
fucked     242   300
fucking    765  1031
hell       951   943
shit      2674  3132
         2011  2012
af        374   554
asap      114   113
chillin   200   139
fam       193   145
lol      9245  9062
sis       185   152
smh       936   759
stfu      122   131
swag      129    75
ugh       411   348
wat       441   338
wtf       516   500
xd        170   223
                2011  2012
HASHgetalljobs   204    62
HASHjobs        1855   529
HASHwinning      180    63

In [93]:
master_df = vulgarities_df.append(slang_df)

In [94]:
master_df = master_df.append(hashtags_df)

In [95]:
master_df

                2011  2012
ass             1959  2034
bitch           1256  1543
bullshit         166   142
damn            1402  1345
fuck            2050  2367
fucked           242   300
fucking          765  1031
hell             951   943
shit            2674  3132
af               374   554
asap             114   113
chillin          200   139
fam              193   145
lol             9245  9062
sis              185   152
smh              936   759
stfu             122   131
swag             129    75
ugh              411   348
wat              441   338
wtf              516   500
xd               170   223
HASHgetalljobs   204    62
HASHjobs        1855   529
HASHwinning      180    63

In [96]:
master_df.to_csv("/Users/sarikasabnis/Documents/GitHub/Graphics_final/data/master_clean_with_frequency.csv")